### ISSUE TITLE
Add composer oauth token 

### ISSUE THREAD

**Issue by micheleorselli** [ideatosrl/vagrant-php-template#11]
A lot of projects runs in the github api rate limit. As the composer docs suggests the way to resolve this is to create a github token.

We could either totally automate token creation and storage (http://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/) or ask the user to provide it (using http://docs.ansible.com/ansible/playbooks_prompts.html)

**Comment by dymissy** [comment]
See https://github.com/ideatosrl/vagrant-php-template/pull/18
